research:
  name: acp
  topic: |
    分析 @google/gemini-cli-core 的acp 协议支持情况，如何使用, 给出一份完整详实的 gemini-cli acp分析报告.
  require:
    node:
      dependencies:
        "@google/gemini-cli-core@0.34.0-preview.0"
overrides: {}
